name: Auto-Clean

on:
  # 每周五上午6点运行（UTC时间：每周四22点）
  schedule:
    - cron: 0 22 * * 4
  # 手动触发
  workflow_dispatch:

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 4     # 保留最近4个发布版本
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0       # 删除所有历史 workflow
